  plugins {
    id 'java' 
    id 'application'
  }

  repositories {
    mavenCentral()
  }

  dependencies {
    implementation 'com.github.twitch4j:twitch4j:1.26.0'

    implementation 'tools.jackson.core:jackson-databind:3.2.0'
    //implementation 'tools.jackson.datatype:jackson-datatype-jsr310:3.0.0-rc2'
    implementation 'tools.jackson.dataformat:jackson-dataformat-yaml:3.2.0'

    implementation 'org.xerial:sqlite-jdbc:3.53.2.0'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.7.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'
  }

  application {
    mainClass.set('com.isthisalis.chataissistant.ChatAIssistant')
  }

  jar {
    manifest.attributes('Main-Class': 'com.isthisalis.chataissistant.ChatAIssistant')
  }

  distributions {
    main {
      contents {
        into('bin') {
          from 'src/main/resources'
        }
      }
    }
  }

  run {
    standardInput = System.in
  }

  tasks.named ('test', Test) {
    useJUnitPlatform()
    maxHeapSize = '1G'

    testLogging {
      events "passed"
    }
  }
