  plugins {
    id 'java' 
    id 'application'
  }

  repositories {
    mavenCentral()
  }

  dependencies {
    implementation('com.github.twitch4j:twitch4j:1.19.0')
    implementation('com.fasterxml.jackson.core:jackson-databind:2.21.4')
    implementation('com.github.twitch4j:twitch4j-chat:1.20.0');
  }

  application {
    mainClass.set('gfs.chataissistant.Main')
  }

  jar {
    manifest.attributes('Main-Class': 'gfs.chataissistant.Main')
  }
